authors:
  cindy_oma:
    name: Cindy Oma
    description: Quality Assurance Specialist | Author | Vlogger | Business Strategist
    avatar: docs/assets/professional/avatar.jpg
    url: http://www.linkedin.com/in/cindy-odoemene